spring:
  profiles: test
  logging:
    path: /test/log/test/
carmall:
  url: jdbc:mysql://localhost:3306/carsource?useUnicode=true&characterEncoding=utf-8
  user: root
  password: nidandan
  maxActive: 8
  typeAliasesPackage: io.dandan.entity
  mapperLocations: classpath*:/io/dandan/mapper/repositories/*.xml
  configLocation: classpath:default-config.xml
  basePackage: io.dandan.mapper
env: test